# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: IcpKit Tests

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
    ios-tests:
        runs-on: macos-26

        steps:
          - uses: actions/checkout@v7

          - name: Select Xcode
            run: sudo xcode-select --switch /Applications/Xcode_26.6.app

          - name: Show environment
            run: |
              xcodebuild -version
              swift --version
              xcrun simctl list devices available

          - name: Run tests
            run: |
              xcodebuild test \
                -scheme IcpKit-Package \
                -destination 'platform=iOS Simulator,name=iPhone 17,OS=latest' \
                -enableCodeCoverage YES \
                -parallel-testing-enabled YES

          - name: Upload coverage
            uses: codecov/codecov-action@v7
            with:
              token: ${{ secrets.CODECOV_TOKEN }}
